version: 0.2

env:
  shell: bash
  # secrets-manager:
    # DOCKER_PASSWORD: $DOCKER_LOGIN_INFORMATION:password
    # DOCKER_LOGIN: $DOCKER_LOGIN_INFORMATION:username
    # DOCKER_PASSWORD_LOCAL_2: $DOCKER_LOGIN_INFORMATION
    # DOCKER_PASSWORD_LOCAL_3: $DOCKER_PASSWORD_ARN:$DOCKER_PASSWORD
    #DOCKER_LOGIN: $DOCKER_LOGIN


phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      # - echo "DOCKER_PASSWORD_ARN =$DOCKER_PASSWORD_ARN"
      # - echo "DOCKER_PASSWORD_LOCAL_2 =$DOCKER_PASSWORD_LOCAL_2"
      # - echo "DOCKER_PASSWORD_LOCAL_3 =$DOCKER_PASSWORD_LOCAL_3"
      - SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id $DOCKER_LOGIN_INFORMATION)
      - DOCKER_PASSWORD=$(echo $SECRET_JSON | jq -r '.SecretString' | jq -r '.password')
      - DOCKER_LOGIN=$(echo $SECRET_JSON | jq -r '.SecretString' | jq -r '.username')
      - echo "docker password = $DOCKER_PASSWORD and Login = $DOCKER_LOGIN"

  build:
    commands:
      - echo Build started on `date`
      - cd blueprints/java/java-lambda-blue-print  # this line must be parametrizable!!
      - echo CREATING BUCKET ......... on `date`
      - bash 1-create-bucket.sh
      - echo BUILDING AND DEPLOYING.........  on `date`
      - bash 2-deploy.sh mvn sonarqube
      - echo TESTING......... on `date`
      - bash 3-invoke.sh
      # - echo CLEANING UP........ on `date`
      # - bash 4-cleanup.sh
  post_build:
    commands:
      - echo Build completed on `date`
